server:
  port: 3003
  context-path: /sell

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true

  main:
    allow-bean-definition-overriding: true

    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  # 接口数据不返回null
#  jackson:
#    default-property-inclusion: non_null

#mybatis:
#  type-aliases-package: com.xiao.xiao1.entity
#  mapper-locations: classpath:com/xiao/xiao1/mapper/*.xml
